"""add_huluxia_adapter_state_table

Revision ID: add_huluxia_state
Revises: 4a364dbb8dab
Create Date: 2026-01-28 18:30:00.000000

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_huluxia_state"
down_revision: Union[str, None] = "4a364dbb8dab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "huluxia_adapter_state",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("adapter_name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.String(length=50), nullable=True),
        sa.Column("key", sa.Text(), nullable=True),
        sa.Column("last_message_time", sa.DateTime(), nullable=True),
        sa.Column("processed_message_ids", sa.Text(), nullable=True),
        sa.Column("key_expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("adapter_name", name="uq_adapter_name"),
    )
    op.create_index(
        "ix_huluxia_adapter_state_adapter_name",
        "huluxia_adapter_state",
        ["adapter_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_huluxia_adapter_state_adapter_name", table_name="huluxia_adapter_state"
    )
    op.drop_table("huluxia_adapter_state")
    # ### end Alembic commands ###
